- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that: "{{ item }}"
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/common/msmtp"
  loop:
    - setup_msmtp == setup_msmtp | bool

- name: check that mandatory variables are correctly defined (msmtp)
  assert:
    quiet: yes
    that: "{{ item }}"
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/common/msmtp"
  when: setup_msmtp | bool
  loop:
    - msmtp_host is not search("CHANGEME")
    - msmtp_port == msmtp_port|int
    - msmtp_auth_enabled == msmtp_auth_enabled | bool
    - msmtp_tls_enabled == msmtp_tls_enabled | bool
    - msmtp_admin_email is not search("CHANGEME")
    - msmtp_from is not search("CHANGEME")
    - msmtp_starttls == msmtp_starttls | bool
    - msmtp_tls_certcheck == msmtp_tls_certcheck | bool

- name: check that mandatory variables are correctly defined (msmtp authentication)
  assert:
    quiet: yes
    that: "{{ item }}"
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/common/msmtp"
  when:
    - setup_msmtp | bool
    - msmtp_auth_enabled | bool
  loop:
    - msmtp_username is not search("CHANGEME")
    - msmtp_password is not search("CHANGEME")
