- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that: "{{ item }}"
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/common/dns"
  loop:
    - dns_nameservers|type_debug == "list"
    - setup_dns == setup_dns | bool

- name: check that DNS resolvers are configured
  assert:
    quiet: yes
    that:
      - dns_nameservers | length != 0
    fail_msg: "setup_dns is set to yes but no resolvers (dns_nameservers) have been configured"
  when: setup_dns | bool
  tags: dns

- name: check that variables are correctly defined (dns_nameservers)
  assert:
    quiet: yes
    that: "{{ item == item | ansible.utils.ipaddr('address') }}"
    fail_msg: "dns_nameservers: {{ item }} is not a valid IP address"
  when: setup_dns | bool
  loop: "{{ dns_nameservers }}"
