- name: remove unwanted packages
  apt:
    state: absent
    package: "{{ packages_remove }}"

- name: install ansible modules requirements
  apt:
    state: present
    package:
      - aptitude # apt module
      - curl # http modules
      - git # git module
      - initramfs-tools
      - unzip # unarchive module
      - zip # unarchive module

- name: install additional packages
  apt:
    state: present
    package: "{{ packages_install }}"

##### HARDWARE-SPECIFIC #####

- name: create ansible facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"

- name: create rdrand fact file
  template:
    src: etc_ansible_facts.d_rdrand.fact.j2
    dest: /etc/ansible/facts.d/rdrand.fact
    mode: "0755"
  notify: update ansible facts
  ignore_errors: "{{ ansible_check_mode }}"

- name: remove files from old versions of the role
  file:
    state: absent
    path: /etc/ansible/facts.d/common.fact
  notify: update ansible facts

# update ansible facts immediately to detect CPU TRNG support
- name: apply configuration (flush handlers)
  meta: flush_handlers

- name: install haveged random number generator if the host is a KVM/VMware VM
  apt:
    state: present
    package: haveged
  when: "('kvm' in ansible_facts.virtualization_tech_guest) or ('VMware' in ansible_facts.virtualization_tech_guest)"

- name: install hardware random number generator support packages if the CPU supports it
  apt:
    state: present
    package: rng-tools5
  when: ansible_local.rdrand.cpu_rdrand
  ignore_errors: "{{ ansible_check_mode }}"

- name: install qemu guest agent if the host is a KVM VM
  apt:
    state: present
    package: haveged
  when: "'kvm' in ansible_facts.virtualization_tech_guest"
