- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that: "{{ item }}"
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/common/ssh"
  loop:
    - setup_ssh == setup_ssh | bool
    - ssh_permit_root_login in ['yes', 'no', 'without-password', 'prohibit-password', 'forced-commands-only']
    - ssh_accept_locale_env == ssh_accept_locale_env | bool
    - ssh_allow_tcp_forwarding in ['no', 'local', 'remote', 'all']
    - ssh_authorized_keys|type_debug == "list"
    - ssh_log_level in ['QUIET', 'FATAL', 'ERROR', 'INFO', 'VERBOSE', 'DEBUG', 'DEBUG1', 'DEBUG2', 'DEBUG3']
    - ssh_server_revoked_keys|type_debug == "list"
    - ssh_sftp_loglevel in ['QUIET', 'FATAL', 'ERROR', 'INFO', 'VERBOSE', 'DEBUG', 'DEBUG1', 'DEBUG2', 'DEBUG3']
