- name: include APT package management configuration tasks
  import_tasks: apt.yml
  become: yes
  tags:
    - common
    - apt
  when: setup_apt | bool

##### UTILITIES ####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- name: include immediate unattended-upgrade tasks
  import_tasks: utils-apt-unattended-upgrade.yml
  become: yes
  tags:
    - never
    - utils-apt-unattended-upgrade

- name: include immediate apt upgrade tasks
  import_tasks: utils-apt-upgrade.yml
  become: yes
  tags:
    - never
    - utils-apt-upgrade
