- name: update pam configuration
  become: yes
  command: 'pam-auth-update --package'
  changed_when: yes

- name: restart systemd-logind
  become: yes
  service:
    name: systemd-logind
    state: restarted
    enabled: yes
