- name: include firewalld configuration tasks
  import_tasks: firewalld.yml
  become: yes
  tags:
    - common
    - firewall
  when: setup_firewall | bool

##### UTILITIES ####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- name: include firewalld status report tasks
  import_tasks: utils-firewalld-info.yml
  become: yes
  tags:
    - never
    - utils-firewalld-info